package br.com.bbseguros.produto.config;

import br.com.bbseguros.produto.domain.Cobertura;
import br.com.bbseguros.produto.repositories.CoberturaRepository;

public class InstanciaCobertura {
	
	
public static void instanciaCobertura(CoberturaRepository coberturaRepo) {
		
		coberturaRepo.save(new Cobertura(null,"COBERTURA GENERICA PARA SINISTRO") );
		coberturaRepo.save(new Cobertura(null,"INDENIZAÇAO ESPECIAL POR ACIDENTE - IEA") );
		coberturaRepo.save(new Cobertura(null,"INVALIDEZ PERMANENTE TOTAL OU PARCIAL POR ACIDENTE - IPA") );
		coberturaRepo.save(new Cobertura(null,"INVALIDEZ PERMANENTE TOTAL POR DOENÇA - IPD") );
		coberturaRepo.save(new Cobertura(null,"MORTE - QUALQUER QUE SEJA A CAUSA DETERMINANTE") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS MÉDICO HOSPITALAR - DMH") );
		coberturaRepo.save(new Cobertura(null,"DIARIA DE INCAPACIDADE TEMPORARIA - DIT") );
		coberturaRepo.save(new Cobertura(null,"ASSISTENCIA 24 H - RESIDENCIA") );
		coberturaRepo.save(new Cobertura(null,"ASSISTENCIA 24 H - VEICULO") );
		coberturaRepo.save(new Cobertura(null,"ASSISTENCIA 24 H - FUNERAL") );
		coberturaRepo.save(new Cobertura(null,"MORTE NATURAL") );
		coberturaRepo.save(new Cobertura(null,"INCENDIO, QUEDA DE RAIO, EXPLOSAO E/OU IMPLOSAO") );
		coberturaRepo.save(new Cobertura(null,"VENDAVAL, FURACAO, CICLONE, TORNADO, GRANIZO E FUMAÇA") );
		coberturaRepo.save(new Cobertura(null,"IMPACTO DE VEICULOS TERRESTRES E QUEDA DE AERONAVES") );
		coberturaRepo.save(new Cobertura(null,"TUMULTOS E MOTINS") );
		coberturaRepo.save(new Cobertura(null,"DANOS ELÉTRICOS") );
		coberturaRepo.save(new Cobertura(null,"DIARIAS POR PARALISAÇAO DE ATIVIDADES") );
		coberturaRepo.save(new Cobertura(null,"PERDA OU DESPESA DE ALUGUEL") );
		coberturaRepo.save(new Cobertura(null,"ROUBO OU FURTO QUALIFICADO DE BENS E MERCADORIAS") );
		coberturaRepo.save(new Cobertura(null,"ROUBO OU FURTO QUALIFICADO DE VALORES - ESTABELECIMENTO") );
		coberturaRepo.save(new Cobertura(null,"ROUBO DE VALORES - EM TRANSITO EM MAOS DE PORTADORES") );
		coberturaRepo.save(new Cobertura(null,"FIDELIDADE DE EMPREGADOS") );
		coberturaRepo.save(new Cobertura(null,"TUMULTO") );
		coberturaRepo.save(new Cobertura(null,"RESPONSABILIDADE CIVIL - ESTABELECIMENTO COMS. E/OU INDS.") );
		coberturaRepo.save(new Cobertura(null,"DETERIORAÇAO DE MERCADORIAS EM AMB. FRIGORIF.") );
		coberturaRepo.save(new Cobertura(null,"LETREIROS E/OU ANUNCIOS LUMINOSOS") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS DE INFORMATICA - PORTATEIS") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS DE INFORMATICA - DEMAIS") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS DE ESCRITORIOS E COMERCIAIS") );
		coberturaRepo.save(new Cobertura(null,"INCENDIO, RAIO E EXPLOSAO DE QUALQUER NATUREZA") );
		coberturaRepo.save(new Cobertura(null,"DESMORONAMENTO E TUMULTO") );
		coberturaRepo.save(new Cobertura(null,"VENDAVAL") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS EMERGENCIAIS") );
		coberturaRepo.save(new Cobertura(null,"PAGAMENTO DE ALUGUEL") );
		coberturaRepo.save(new Cobertura(null,"MICROCOMPUTADOR E RESPECTIVOS EQUIPAMENTOS") );
		coberturaRepo.save(new Cobertura(null,"ROUBO DE JOIAS E PRECIOSIDADES") );
		coberturaRepo.save(new Cobertura(null,"ROUBO DE APARELHOS DE SOM E IMAGEM") );
		coberturaRepo.save(new Cobertura(null,"ROUBO DE MOVEIS E UTENSILIOS") );
		coberturaRepo.save(new Cobertura(null,"RESPONSABILIDADE CIVIL FAMILIAR") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS FIXAS PERDURAVEIS (DEC. DANOS ELÉTRICOS)") );
		coberturaRepo.save(new Cobertura(null,"PROPRIEDADES CIRCUNVIZINHAS") );
		coberturaRepo.save(new Cobertura(null,"RESPONSABILIDADE CIVIL CONDOMINIO") );
		coberturaRepo.save(new Cobertura(null,"VENDAVAL/FUMAÇA") );
		coberturaRepo.save(new Cobertura(null,"QUEBRA DE VIDROS") );
		coberturaRepo.save(new Cobertura(null,"TUMULTOS, GREVES E LOCK-OUT") );
		coberturaRepo.save(new Cobertura(null,"ROUBO DE BENS DO CONDOMINIO") );
		coberturaRepo.save(new Cobertura(null,"VIDA") );
		coberturaRepo.save(new Cobertura(null,"AP. MORTE/INV. PERMANENTE (EMPREGADOS)") );
		coberturaRepo.save(new Cobertura(null,"AP. MORTE (EMPREGADOS)") );
		coberturaRepo.save(new Cobertura(null,"AP. INV. PERMANENTE (EMPREGADOS)") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL - 50 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL - 51 ATÉ 250 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - INC./ROUBO - 50 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - INC./ROUBO - 51 ATÉ 250 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS INSTALAÇAO NOVO LOCAL") );
		coberturaRepo.save(new Cobertura(null,"FIDELIDADE") );
		coberturaRepo.save(new Cobertura(null,"INCENDIO, RAIO E EXPLOSAO DE GAS DOMÉSTICO") );
		coberturaRepo.save(new Cobertura(null,"RESP. CIVIL GERAL  E RESP. CIVIL CRUZADA") );
		coberturaRepo.save(new Cobertura(null,"LUCROS CESSANTES ( DEC. VENDAVAL/FUMAÇA)") );
		coberturaRepo.save(new Cobertura(null,"VIDA (MORTE NATURAL/ACIDENTAL)") );
		coberturaRepo.save(new Cobertura(null,"ACIDENTES PESSOAIS (MORTE)") );
		coberturaRepo.save(new Cobertura(null,"ACIDENTES PESSOAIS (INV.PERMANENTE)") );
		coberturaRepo.save(new Cobertura(null,"PERDA DE ALUGUEL") );
		coberturaRepo.save(new Cobertura(null,"LUCROS CESSANTES (DEC. COBERTURA BASICA)") );
		coberturaRepo.save(new Cobertura(null,"RESPONSABILIDADE CIVIL CRUZADA") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS ELETRONICOS") );
		coberturaRepo.save(new Cobertura(null,"INCENDIO, RAIO E EXPLOSAO DE GAS DE USO DOMÉSTICO..") );
		coberturaRepo.save(new Cobertura(null,"DANOS ELÉTRICOS.") );
		coberturaRepo.save(new Cobertura(null,"EXPLOSAO DE QUALQUER NATUREZA") );
		coberturaRepo.save(new Cobertura(null,"EXPLOSAO FISICA") );
		coberturaRepo.save(new Cobertura(null,"EXPLOSAO QUIMICA") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA INCENDIO/ROUBO/FURTO QUALIFICADO") );
		coberturaRepo.save(new Cobertura(null,"VAZAMENTO DE SPRINKLERS") );
		coberturaRepo.save(new Cobertura(null,"INCENDIO DECORRENTE DE QUEIMADA ZONA RURAL") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS ESTACIONARIOS") );
		coberturaRepo.save(new Cobertura(null,"RISCOS DIVERSOS.") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS ELETRONICOS COM ROUBO/FURTO QUALIFICADO") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS CINEMATOGRAFICOS") );
		coberturaRepo.save(new Cobertura(null,"QUEBRA DE MAQUINAS") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS ARRENDADOS/CEDIDOS TERCEIROS") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS MOVEIS NO LOCAL DE RISCO") );
		coberturaRepo.save(new Cobertura(null,"DESMORONAMENTO") );
		coberturaRepo.save(new Cobertura(null,"TUMULTOS, GREVES E LOCK-OUT - RESIDENCIAL") );
		coberturaRepo.save(new Cobertura(null,"TUMULTOS, GREVES E LOCK-OUT - COMERCIAL") );
		coberturaRepo.save(new Cobertura(null,"DANOS MORAIS - EMPREGADOR") );
		coberturaRepo.save(new Cobertura(null,"ROUBO E/OU FURTO QUALIFICADO") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL - 251 ATÉ 500 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL - ACIMA DE 500 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - INC./ROUBO - 251 ATÉ 500 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - INC./ROUBO - ACIMA DE 500 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"DANOS MORAIS - RISCOS CONTINGENTES VEICULOS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO - ATÉ 50 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO - 51 ATÉ 250 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO - 251 ATÉ 500 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO - ACIMA DE 500 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"QUEDA DE AERONAVES") );
		coberturaRepo.save(new Cobertura(null,"IMPACTO DE VEICULOS") );
		coberturaRepo.save(new Cobertura(null,"RESPONSABILIDADE CIVIL DO SINDICO") );
		coberturaRepo.save(new Cobertura(null,"VALORES NO INTERIOR DE ESTABELECIMENTO") );
		coberturaRepo.save(new Cobertura(null,"VALORES EM TRANSITO") );
		coberturaRepo.save(new Cobertura(null,"REMOÇAO DE ENTULHO") );
		coberturaRepo.save(new Cobertura(null,"R.C. OPERAÇOES") );
		coberturaRepo.save(new Cobertura(null,"ALAGAMENTO") );
		coberturaRepo.save(new Cobertura(null,"ANUNCIOS LUMINOSOS") );
		coberturaRepo.save(new Cobertura(null,"ALAGAMENTO / INUNDAÇAO (EXCLUINDO RESSACA)") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS COM RECOMPOSIÇAO DE DOCUMENTOS") );
		coberturaRepo.save(new Cobertura(null,"QUEBRA DE VIDROS E ANUNCIOS LUMINOSOS") );
		coberturaRepo.save(new Cobertura(null,"ACIDENTES PESSOAIS (MORTE/INVALIDEZ PERMANENTE)") );
		coberturaRepo.save(new Cobertura(null,"ACIDENTES PESSOAIS - MORTE") );
		coberturaRepo.save(new Cobertura(null,"ACIDENTES PESSOAIS - INVALIDEZ PERMANENTE") );
		coberturaRepo.save(new Cobertura(null,"ATOS DOLOSOS") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS COM INSTALAÇAO NOVO LOCAL (DEC. BASICA)") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS COM DESENTULHO (DEC. BASICA)") );
		coberturaRepo.save(new Cobertura(null,"PERDA OU PAGAMENTO DE ALUGUEL (DEC. BASICA)") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS FIXAS PERDURAVEIS (DEC. BASICA)") );
		coberturaRepo.save(new Cobertura(null,"LUCRO LIQUIDO (DEC. BASICA)") );
		coberturaRepo.save(new Cobertura(null,"LUCRO BRUTO (DEC. BASICA)") );
		coberturaRepo.save(new Cobertura(null,"HONORARIOS DE PERITO (DEC. BASICA)") );
		coberturaRepo.save(new Cobertura(null,"RISCOS CONTINGENTES") );
		coberturaRepo.save(new Cobertura(null,"BAGAGENS 30 DIAS") );
		coberturaRepo.save(new Cobertura(null,"OBRAS DE ARTE") );
		coberturaRepo.save(new Cobertura(null,"TERREMOTO, MAREMOTO E TREMORES TERRESTRES") );
		coberturaRepo.save(new Cobertura(null,"INCENDIO, RAIO E EXPLOSAO DE QUALQUER NATUREZA") );
		coberturaRepo.save(new Cobertura(null,"PAGAMENTO E PERDA DE ALUGUEL") );
		coberturaRepo.save(new Cobertura(null,"TUMULTOS, GREVES E MOTINS") );
		coberturaRepo.save(new Cobertura(null,"PRATICANTES DE GOLF") );
		coberturaRepo.save(new Cobertura(null,"QUEBRA DE MAQUINAS") );
		coberturaRepo.save(new Cobertura(null,"DANOS ELETRICOS") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS COM DESENTULHO") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS COM INSTALAÇAO NOVO LOCAL") );
		coberturaRepo.save(new Cobertura(null,"RC ESTABELECIMENTOS DE HOSPEDAGEM, REST., BARES, BOITES") );
		coberturaRepo.save(new Cobertura(null,"DESPESAS FIXAS PERDURAVEIS") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS ELETRONICOS INCLUSIVE ROUBO") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS ELETRONICOS PORTATEIS C/ROUBO/FURTO") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS PORTATEIS NAO ELETRONICOS C/ROUBO/FURTO") );
		coberturaRepo.save(new Cobertura(null,"EXTRAVAZAMENTO DE MATERIAIS EM ESTADO DE FUSAO") );
		coberturaRepo.save(new Cobertura(null,"FLUTUANTE EM LOCAIS NAO ESPECIFICADOS") );
		coberturaRepo.save(new Cobertura(null,"GREVES/TUMULTOS/LOCK-OUT CLASSE 1") );
		coberturaRepo.save(new Cobertura(null,"GREVES/TUMULTOS/LOCK-OUT CLASSE 2") );
		coberturaRepo.save(new Cobertura(null,"GREVES/TUMULTOS/LOCK-OUT CLASSE 3") );
		coberturaRepo.save(new Cobertura(null,"HONORARIOS DE PERITO") );
		coberturaRepo.save(new Cobertura(null,"IMPACTO DE VEICULOS TERRESTRES") );
		coberturaRepo.save(new Cobertura(null,"INCENDIO, INCL. DEC. TUMULTOS, RAIO E EXPL. GAS DOMEST.") );
		coberturaRepo.save(new Cobertura(null,"INCENDIO, INCL. DEC. TUMULTOS, RAIO E EXPL. QQ NATUREZA") );
		coberturaRepo.save(new Cobertura(null,"INTERRUPÇAO DE NEGOCIOS") );
		coberturaRepo.save(new Cobertura(null,"LUCRO BRUTO") );
		coberturaRepo.save(new Cobertura(null,"LUCRO LIQUIDO") );
		coberturaRepo.save(new Cobertura(null,"MOVIMENTAÇAO INTERNA") );
		coberturaRepo.save(new Cobertura(null,"R.C. CHAPAS DE EXPERIENCIA (DANOS AO VEICULO)") );
		coberturaRepo.save(new Cobertura(null,"R.C. CHAPAS DE EXPERIENCIA (DANOS PELO VEICULO)") );
		coberturaRepo.save(new Cobertura(null,"R.C. OPERAÇOES/EMPREGADOR/CONT. VEICULOS") );
		coberturaRepo.save(new Cobertura(null,"R.C. TEST DRIVE (DANOS AO VEICULO)") );
		coberturaRepo.save(new Cobertura(null,"R.C. TEST DRIVE (DANOS PELO VEICULO)") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO - ATÉ 10 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO - ATÉ 20 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO - ATÉ 30 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO - ATÉ 40 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - COLISAO - ACIMA 40 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL - ATÉ 10 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL - ATÉ 20 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL - ATÉ 30  VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL - ATÉ 40 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - GLOBAL - ACIMA 40 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - INC./ROUBO - ATÉ 10 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - INC./ROUBO - ATÉ 20 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - INC./ROUBO - ATÉ 30 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - INC./ROUBO - ATÉ 40 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"R.C. GARAGISTA - INC./ROUBO - ACIMA 40 VAGAS") );
		coberturaRepo.save(new Cobertura(null,"RESPONSABILIDADE CIVIL LOJISTA P/ SHOPPING CENTER") );
		coberturaRepo.save(new Cobertura(null,"TERREMOTO/MAREMOTO") );
		coberturaRepo.save(new Cobertura(null,"VALORES EM TRANSITO EM MAOS DE PORTADORES") );
		coberturaRepo.save(new Cobertura(null,"INCENDIO,  RAIO E EXPLOSAO DE  GAS DOMÉSTICO") );
		coberturaRepo.save(new Cobertura(null,"VERBA FRETE") );
		coberturaRepo.save(new Cobertura(null,"VERBA FOB") );
		coberturaRepo.save(new Cobertura(null,"VANDALISMO") );
		coberturaRepo.save(new Cobertura(null,"DANOS MORAIS") );
		coberturaRepo.save(new Cobertura(null,"ROUBO DE BENS (EXCLUIDAS OBRAS DE ARTE)") );
		coberturaRepo.save(new Cobertura(null,"CONFORME CONDIÇOES GERAIS E/OU ESPECIFICAS") );
		coberturaRepo.save(new Cobertura(null,"RESPONSABILIDADE CIVIL GARAGISTA SEM ROUBO") );
		coberturaRepo.save(new Cobertura(null,"COBERTURA BASICA 01 - PT/AS") );
		coberturaRepo.save(new Cobertura(null,"COBERTURA BASICA 02 - PT/AS/RCA") );
		coberturaRepo.save(new Cobertura(null,"COBERTURA BASICA 03 - PT/AS/RCA/AP") );
		coberturaRepo.save(new Cobertura(null,"COBERTURA BASICA 03.A - PT/AS/RCA/AP") );
		coberturaRepo.save(new Cobertura(null,"COBERTURA BASICA 02.A - PT/AS/RCA") );
		coberturaRepo.save(new Cobertura(null,"COBERTURA BASICA 01.A - PT/AS") );
		coberturaRepo.save(new Cobertura(null,"DANOS MATERIAIS / PESSOAIS A TERCEIROS") );
		coberturaRepo.save(new Cobertura(null,"INSTALAÇAO / MONTAGEM") );
		coberturaRepo.save(new Cobertura(null,"OBRAS CIVIS EM CONTRUÇAO") );
		coberturaRepo.save(new Cobertura(null,"OBRAS CIVIS EM CONTRUÇAO / INSTALAÇAO-MONTAGEM") );
		coberturaRepo.save(new Cobertura(null,"RESPONSABILIDADE CIVIL - P & I") );
		coberturaRepo.save(new Cobertura(null,"RISCO AERONAUTICO") );
		coberturaRepo.save(new Cobertura(null,"RISCO DE TRANSPORTE IDA / VOLTA") );
		coberturaRepo.save(new Cobertura(null,"RISCO FERROVIARIO") );
		coberturaRepo.save(new Cobertura(null,"RISCO MARITIMO") );
		coberturaRepo.save(new Cobertura(null,"RISCO RODOVIARIO") );
		coberturaRepo.save(new Cobertura(null,"TRANSPORTE INTERNO LOCAL RISCO") );
		coberturaRepo.save(new Cobertura(null,"GARANTIA BASICA CASCO") );
		coberturaRepo.save(new Cobertura(null,"GARANTIA RETA") );
		coberturaRepo.save(new Cobertura(null,"CAIXA FORTE") );
		coberturaRepo.save(new Cobertura(null,"DANOS FISICOS") );
		coberturaRepo.save(new Cobertura(null,"QUEBRA DE GARANTIA") );
		coberturaRepo.save(new Cobertura(null,"RCF - RCARGA") );
		coberturaRepo.save(new Cobertura(null,"RCF - DESAPARECIMENTO DE CARGA") );
		coberturaRepo.save(new Cobertura(null,"DANOS AO IMOVEL") );
		coberturaRepo.save(new Cobertura(null,"INADIMPLENCIA") );
		coberturaRepo.save(new Cobertura(null,"MULTAS CONTRATUAIS") );
		coberturaRepo.save(new Cobertura(null,"COBERTURA BASICA") );
		coberturaRepo.save(new Cobertura(null,"FORNECEDOR") );
		coberturaRepo.save(new Cobertura(null,"PRESTADOR DE SERVIÇO") );
		coberturaRepo.save(new Cobertura(null,"CONCORRENTE") );
		coberturaRepo.save(new Cobertura(null,"CONSTRUTOR") );
		coberturaRepo.save(new Cobertura(null,"SEGUIMENTO IMOBILIARIO") );
		coberturaRepo.save(new Cobertura(null,"ADIANTAMENTO DE PAGAMENTO") );
		coberturaRepo.save(new Cobertura(null,"RCTA - CARGA - AMPLA") );
		coberturaRepo.save(new Cobertura(null,"RCTA - CARGA - RESTRITA") );
		coberturaRepo.save(new Cobertura(null,"RCTRODOVIARIO - CARGA") );
		coberturaRepo.save(new Cobertura(null,"MORTE ACIDENTAL") );
		coberturaRepo.save(new Cobertura(null,"RETIRADA E COLOCAÇAO NA AGUA") );
		coberturaRepo.save(new Cobertura(null,"ESPECIAL NR 8 RESP CIVIL (P & I)") );
		coberturaRepo.save(new Cobertura(null,"LIMITE DE RESPONSABILIDADE") );
		coberturaRepo.save(new Cobertura(null,"CLASSE 1 - PASSAGEIROS") );
		coberturaRepo.save(new Cobertura(null,"CLASSE 2 - TRIPULANTES") );
		coberturaRepo.save(new Cobertura(null,"CLASSE 3/4 - TERC BENS SOLO") );
		coberturaRepo.save(new Cobertura(null,"GARANTIA RC 2 RISCO") );
		coberturaRepo.save(new Cobertura(null,"BAGAGEM PASSAGEIROS") );
		coberturaRepo.save(new Cobertura(null,"BAGAGEM TRIPULANTES") );
		coberturaRepo.save(new Cobertura(null,"RESPONSABILIDADE CIVIL PORTUARIA") );
		coberturaRepo.save(new Cobertura(null,"BENS MOVEIS E IMOVEIS") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS MOVEIS - T.N.") );
		coberturaRepo.save(new Cobertura(null,"RC GUARDA DE VEICULOS") );
		coberturaRepo.save(new Cobertura(null,"RC EMPREGADOR") );
		coberturaRepo.save(new Cobertura(null,"RC  CONTINGENTES DE VEICULOS") );
		coberturaRepo.save(new Cobertura(null,"RC - ARMAZÉNS GERAIS E SIMILARES") );
		coberturaRepo.save(new Cobertura(null,"RC - OP. DE CARGA, DESC., MOV., IÇAMENTO OU DESCIDA (AMPLA") );
		coberturaRepo.save(new Cobertura(null,"FERMENTAÇAO EXPONTANEA") );
		coberturaRepo.save(new Cobertura(null,"POLUIÇAO SUBITA") );
		coberturaRepo.save(new Cobertura(null,"ADUANEIRO") );
		coberturaRepo.save(new Cobertura(null,"RETENÇAO DE PAGAMENTO") );
		coberturaRepo.save(new Cobertura(null,"DOENÇA TERMINAL - D.T") );
		coberturaRepo.save(new Cobertura(null,"RC PRODUTOS - T.N.") );
		coberturaRepo.save(new Cobertura(null,"RISCOS DIVERSOS") );
		coberturaRepo.save(new Cobertura(null,"CIRCULAÇAO DE EQUIPAMENTOS ADJACENCIAS") );
		coberturaRepo.save(new Cobertura(null,"DANOS A EQUIPAMENTOS DE TERCEIROS") );
		coberturaRepo.save(new Cobertura(null,"DANOS A MERCADORIAS DE TERCEIROS") );
		coberturaRepo.save(new Cobertura(null,"CARGA E DESCARGA E/OU IÇAMENTO") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS EM EXPOSIÇAO") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS EM EXPOSIÇAO INCLUINDO TRANSPORTE") );
		coberturaRepo.save(new Cobertura(null,"INSTRUMENTOS MUSICAIS E EQUIPAMENTOS DE SOM") );
		coberturaRepo.save(new Cobertura(null,"EQUIPAMENTOS ELETRONICOS/INFORMATICA") );
		coberturaRepo.save(new Cobertura(null,"R. C. GUARDA DE VEICULOS TERCEIROS") );
		coberturaRepo.save(new Cobertura(null,"RC  OPERAÇOES - CARGA E DESCARGA (COBERTURA AMPLA)") );
		coberturaRepo.save(new Cobertura(null,"FLUTUANTES EM LOCAIS ESPECIFICADOS") );
		
	}

}
